USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS &{ctx.env.SNOWFLAKE_ROLE};
GRANT ROLE &{ctx.env.SNOWFLAKE_ROLE} TO USER &{ctx.env.SNOWFLAKE_USER};
-- Database that will hold all demo data
CREATE DATABASE IF NOT EXISTS &{ctx.env.SNOWFLAKE_DATABASE};
GRANT OWNERSHIP ON DATABASE &{ctx.env.SNOWFLAKE_DATABASE} TO &{ctx.env.SNOWFLAKE_ROLE};
GRANT OWNERSHIP ON SCHEMA &{ctx.env.SNOWFLAKE_DATABASE}.PUBLIC TO &{ctx.env.SNOWFLAKE_ROLE};